# Generated by Django 5.0.6 on 2024-08-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0024_alter_payment_organization_alter_payment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_darja',
            field=models.CharField(choices=[('Duwwam', 'Duwwam'), ('Awwal', 'Awwal'), ('Suwwaam', 'Suwwaam')], default='Duwwam', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Khajabagh', 'Khajabagh'), ('Akberbagh', 'Akberbagh'), ('branch3', 'Branch 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Mahad_e_Alim', 'Mahad e Alim'), ('course2', 'Course 2'), ('course3', 'Course 3')], max_length=20),
        ),
    ]
