# Generated by Django 5.0.6 on 2024-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0025_student_class_darja_alter_student_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('Khajabagh', 'Khajabagh'), ('Akberbagh', 'Akberbagh'), ('branch3', 'Branch 3')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_darja',
            field=models.CharField(blank=True, choices=[('Duwwam', 'Duwwam'), ('Awwal', 'Awwal'), ('Suwwaam', 'Suwwaam')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('Mahad_e_Alim', 'Mahad e Alim'), ('course2', 'Course 2'), ('course3', 'Course 3')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='monthly_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
