# Generated by Django 5.0.6 on 2024-08-28 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0026_alter_student_branch_alter_student_class_darja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.AddField(
            model_name='payment',
            name='student_admission_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.student', to_field='admission_number'),
        ),
    ]
