# Generated by Django 5.0.6 on 2024-08-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0028_rename_student_admission_number_payment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_type',
            field=models.CharField(choices=[('Library Fee', 'Library Fee'), ('Hostel Fee', 'Hostel Fee'), ('Academic Fee', 'Academic Fee'), ('Mess Fee', 'Mess Fee'), ('Admission Fee', 'Admission Fee'), ('Examination Fee', 'Examination Fee'), ('Stationary Fee', 'Stationary Fee'), ('Other', 'Other')], max_length=100),
        ),
    ]
