# Generated by Django 5.0.6 on 2024-09-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0029_alter_payment_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
