# Generated by Django 5.0.6 on 2024-09-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0030_alter_payment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_type',
            field=models.CharField(choices=[('Library Fee', 'Library Fee'), ('Hostel Fee', 'Hostel Fee'), ('Academic Fee', 'Academic Fee'), ('Mess Fee', 'Mess Fee'), ('Admission Fee', 'Admission Fee'), ('Exam Fee', 'Exam Fee'), ('Stationary Fee', 'Stationary Fee'), ('Other', 'Other')], max_length=100),
        ),
    ]
